# Generated by Django 4.1.13 on 2024-09-19 07:40

import common.db.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_auto_20230110_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketflow',
            name='name',
            field=models.CharField(default='Default', max_length=256, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ticketflow',
            name='priority',
            field=models.IntegerField(default=50, help_text='1-100, the lower the value will be match first', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='ticketflow',
            name='users',
            field=common.db.fields.JSONManyToManyField(default=dict, to='users.User', verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='ticketflow',
            name='internal',
            field=models.BooleanField(default=True, verbose_name='Internal'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketflow',
            unique_together={('name', 'org_id', 'type')},
        ),
    ]
